# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reise',
            options={'verbose_name_plural': 'Reisen'},
        ),
        migrations.AlterModelOptions(
            name='reisetage',
            options={'verbose_name_plural': 'Reisetage'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tage'},
        ),
        migrations.AddField(
            model_name='tag',
            name='titel',
            field=models.CharField(default=b'', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reise',
            name='titel',
            field=models.CharField(max_length=1024),
        ),
    ]
